version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform.zip && mv terraform /usr/local/bin/
      - terraform --version
  build:
    commands:
      - echo "Initializing Terraform"
      - terraform init
      - echo "Planning Terraform Deployment"
      - terraform plan
      - echo "Applying Terraform Configuration"
      - terraform apply -auto-approve

